export const translationsFolderPath = "C:/Program Files (x86)/Steam/steamapps/common/SCP Secret Laboratory/Translations";
export const workDirectoryPath = "work";
export const translationsOutputPath = workDirectoryPath + "/Translations";
export const dataFolderPath = "data";
export const scp914RecipesFilePath = dataFolderPath + "/scp-914-recipes.json";
export const itemsFilePath = "/Items.txt";
export const classDescriptionsFilePath = "/Class_Descriptions.txt"
export const facilityFilePath = "/Facility.txt"
export const youAreTextIndex = 31;
export const invisibleCharacter = "ㅤ"